image: hugomods/hugo:exts
#optional if theme wont load 
variables:
  GIT_SUBMODULE_STRATEGY: recursive   # if your theme is a git submodule
test:
  script:
    - hugo --minify --baseURL="${CI_PAGES_URL}/"
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
# Run only on the default branch
create-pages:
  stage: deploy
  script:
    - hugo --minify --baseURL="${CI_PAGES_URL}/"
  pages: true
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH